image: bitriseio/docker-android

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - ".gradle/caches"
    - ".gradle/wrapper"

buildAndroid:
  stage: build
  script:
    - ./gradlew assembleDebug
    - cp app/build/outputs/apk/app-mockdata-debug.apk ./
    - cp app/build/outputs/apk/app-productionAPI-debug.apk ./
  artifacts:
    paths:
      - app-mockdata-debug.apk
      - app-productionAPI-debug.apk
