image: jacekmarchwicki/android

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

buildAndroid:
  stage: build
  script:
    - docker run --tty --interactive --volume=$(pwd):/opt/workspace --workdir=/opt/workspace --rm jacekmarchwicki/android:java7  /bin/sh -c "./gradlew build"
