image: jacekmarchwicki/android

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

buildAndroid:
  stage: build
  script:
    - ./gradlew assembleDebug
